name:  AuctionTrade
version:  0.1
description:  Player can trade items
author:  ibhh
website: http://www.ibhh.de/AuctionTrade

main: me.ibhh.AuctionTrade.AuctionTrade

commands:
  xpShop:
    description: player gets xp for money.
    usage: /AuctionTrade
permissions:
  AuctionTrade.*:
    description: Gives access to all xpShop commands
    children:
      AuctionTrade.create: false
    description: Creates a new auction.
    default: false